### ISSUE TITLE
NameError: global name 'platform' is not defined

### ISSUE THREAD

**Issue by daveyarwood** [pwoolcoc/goenv#15]
Hi,

Trying out a fresh install (via `pip install pygoenv`) of `goenv` produces this error:

```
$ goenv

USING requests
.
Traceback (most recent call last):
  File "/usr/local/bin/goenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/goenv/__init__.py", line 68, in main
    impl(version, *gopath, install_only=install_only, quiet=quiet).go()
  File "/usr/local/lib/python2.7/site-packages/goenv/platform.py", line 187, in __init__
    v, _, _ = platform.mac_ver()
NameError: global name 'platform' is not defined
```

I tried uninstalling and reinstalling via `sudo pip install pygoenv`, with the same result.

**Comment by pwoolcoc** [comment]
Sorry about that! I don't have a Mac to test with, so unfortunately my level of support here is going to be pretty low. I just pushed a new version to PyPi, so please try the latest version (1.6.0) and let me know if it works for you.

**Comment by daveyarwood** [comment]
Just reinstalled via `pip install pygoenv` and tried again, and I got this error:

```
$ goenv
Downloading http://storage.googleapis.com/golang/go1.5.2.darwin-amd64-osx10.8.tar.gz
KB [################################] 1/1 - 00:00:00
Extracting /Users/dave/.cache/goenv/go1.5.2.darwin-amd64-osx10.8.tar.gz to /Users/dave/.config/goenv/dists/1.5.2
Traceback (most recent call last):
  File "/usr/local/bin/goenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/goenv/__init__.py", line 68, in main
    impl(version, *gopath, install_only=install_only, quiet=quiet).go()
  File "/usr/local/lib/python2.7/site-packages/goenv/platform_dependent.py", line 100, in go
    godir = self.extract(self.download())
  File "/usr/local/lib/python2.7/site-packages/goenv/platform_dependent.py", line 158, in extract
    with tarfile.open(filename) as tarball:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1672, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by ttacon** [comment]
@daveyarwood Could you check if the downloaded tarball is actually a tarball? Looking at the downloads, it seems to me the issue here is extra filename suffix `-osx10.8` as the filename as provided doesn't exist. If https://github.com/pwoolcoc/goenv/blob/748b061c2a571cb2ee65411fabdfd664802cf22c/goenv/platform_dependent.py#L196 is changed to not use the osx version, it works for me.

**Comment by daveyarwood** [comment]
Aha -- that was the issue exactly. I tried extracting the tarball manually and it didn't recognize the archive format. I tried out your PR and it worked. I've got it working now. Thanks!
